services:
  frontend:
    build: .
    tty: true
    working_dir: /home/node/app
    command: "npm start"
    ports:
      - "127.0.0.1:3001:9090"
    environment:
      - PORT=9090
      - PUBLIC_URL=${PUBLIC_URL}/api/zoomapp/proxy
      - REACT_APP_PUBLIC_ROOT=${PUBLIC_URL}
      - REACT_APP_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - REACT_APP_AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules